import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Chats",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const storeCookies = await cookies();
  // const token = storeCookies.get("chattoken");
  // console.log(token);

  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
