import type { Metadata } from "next";
import AppNavbar from "@/components/navbar/navbar";
import Sidebar from "@/components/sidebar/page";
import { Separator } from "@/components/ui";

export const metadata: Metadata = {
  title: "Chats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        {/* <AppNavbar /> */}
        
        {children}
      </body>
    </html>
  );
}
